// This file is automatically generated based on the file `./generated.rs.tera` when `cargo gen-syntax` is run
// Do not edit manually

//! This module contains auto-generated Rust AST. Like `SyntaxNode`s, AST nodes
//! are generic over ownership: `X<'a>` things are `Copy` references, `XNode`
//! are Arc-based. You can switch between the two variants using `.owned` and
//! `.borrowed` functions. Most of the code works with borrowed mode, and only
//! this mode has all AST accessors.

use rowan::TransparentNewType;

use crate::{
    SyntaxNode, SyntaxKind::*,
    syntax_node::{TreeArc},
    ast::{self, AstNode},
};


// Chunk
#[derive(Debug, PartialEq, Eq, Hash)]
#[repr(transparent)]
pub struct Chunk {
    pub(crate) syntax: SyntaxNode,
}

unsafe impl TransparentNewType for Chunk {
    type Repr = rowan::SyntaxNode;
}

impl AstNode for Chunk {
    fn cast(syntax: &SyntaxNode) -> Option<&Self> {
        match syntax.kind() {
            CHUNK => Some(Chunk::from_repr(syntax.into_repr())),
            _ => None,
        }
    }
    fn syntax(&self) -> &SyntaxNode { &self.syntax }
}

impl ToOwned for Chunk {
    type Owned = TreeArc<Chunk>;
    fn to_owned(&self) -> TreeArc<Chunk> { TreeArc::cast(self.syntax.to_owned()) }
}


impl Chunk {}

